apiVersion: apps/v1
kind: Deployment
metadata:
  name: svelte-frontend
  labels:
    app: party-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svelte-frontend
  template:
    metadata:
      labels:
        app: svelte-frontend
    spec:
      containers:
      - name: svelte-frontend
        image: registry.localhost/party-game/svelte-frontend
        imagePullPolicy: Always
        
        resources:
          requests:
            memory: 256Mi
            cpu: 200m
          limits:
            memory: 768Mi
            cpu: 500m

        ports:
        - containerPort: 4173
        
---

apiVersion: v1
kind: Service
metadata:
  name: svelte-frontend
  labels:
    app: party-game
spec:
  selector:
    app: svelte-frontend
  ports:
  - port: 80
    targetPort: 4173