apiVersion: v1
kind: PersistentVolume
metadata:
  name:  task-game-postgresql
  labels:
    app: party-game
spec:
  storageClassName:  task-game-postgresql
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/bifrost/k3s-volumes/task-game/postgresql

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  task-game-postgresql
  labels:
    app: party-game
spec:
  storageClassName:  task-game-postgresql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: task-game-postgres
  labels:
    app: party-game
spec:
  replicas: 1
  selector:
    matchLabels:
      service: task-game-postgres
  template:
    metadata:
      labels:
        service: task-game-postgres
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: task-game-postgresql

      containers:
      - name: postgres
        image: postgres:15.1
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: task-game-postgresql
                key: database-name
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: task-game-postgresql
                key: database-username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: task-game-postgresql
                key: database-password

        resources:
          limits:
            memory: 256Mi
            cpu: 250m
          requests:
            memory: 128Mi
            cpu: 100m

        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name:  storage
---
apiVersion: v1
kind: Service
metadata:
  name: task-game-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    service: task-game-postgres
