apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf.template: |
      server {
          listen       80;
          # server_name  game.thehuginn.com;

          location /api/game/ {
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_set_header Host $http_host;
              proxy_redirect off;
              proxy_pass http://game-service/;
          }

          location /api/task/ {
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_set_header Host $http_host;
              proxy_redirect off;
              proxy_pass http://task-game/;
          }

          location / {
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_set_header Host $http_host;
              proxy_redirect off;
              proxy_pass http://svelte-frontend;
          }
      }
      
---
              
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: default.conf.template
              path: default.conf.template

      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/templates
          readOnly: true

        resources:
          limits:
            memory: 64Mi
            cpu: 100m
          requests:
            memory: 192Mi
            cpu: 200m

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: drinking-game
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80